import Footer from "@/app/(primary)/component/footer";
import Header from "@/app/(primary)/component/header";

// export const metadata = {
//   title: "Homepage",
//   description: "Generated by create next app",
// };

export default function Layout({ children }) {
  return (
    <html lang="en">
    <body>
      <Header />
      {children}
      <Footer />
    </body>
  </html>
  )
}